#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate DEG between-group comparison job files from sample_info.csv.

Usage:
    python getGroups.py <sample_info.csv> <DEG_dir> [control_group] [compare_dir]

Looks in <DEG_dir> for <treatment>_vs_<control>_{UP,DOWN,ALL}.DEGs.txt (generated by enrich.sh)
and writes job files for all pairwise combinations of treatment groups:
    <compare_dir>/combination/<A>_<r1>_<B>_<r2>
Each file has two lines (DEG file path + set name) and is consumed by run_deg_compare.R.
The group column is taken from the header name "group"; the control group name is configurable (default control).
"""
import csv
import os
import sys


def main():
    if len(sys.argv) < 3:
        sys.exit(__doc__)
    infile, deg_dir = sys.argv[1], sys.argv[2]
    control = sys.argv[3] if len(sys.argv) > 3 else "control"
    compare_dir = sys.argv[4] if len(sys.argv) > 4 else "6.DEGcompare"

    groups = []
    with open(infile, newline="", encoding="utf-8-sig") as fh:
        reader = csv.DictReader(fh)
        for row in reader:
            g = (row.get("group") or "").strip()
            if g and g not in groups and g != control:
                groups.append(g)

    os.makedirs(os.path.join(compare_dir, "combination"), exist_ok=True)
    for i in range(len(groups)):
        for j in range(i + 1, len(groups)):
            for r1 in ("UP", "DOWN", "ALL"):
                for r2 in ("UP", "DOWN", "ALL"):
                    out = os.path.join(compare_dir, "combination",
                                       f"{groups[i]}_{r1}_{groups[j]}_{r2}")
                    with open(out, "w") as f:
                        a = os.path.join(deg_dir, f"{groups[i]}_vs_{control}_{r1}.DEGs.txt")
                        b = os.path.join(deg_dir, f"{groups[j]}_vs_{control}_{r2}.DEGs.txt")
                        print(f"{a} {groups[i]}_{r1}", file=f)
                        print(f"{b} {groups[j]}_{r2}", file=f)
    print(f"[getGroups] {len(groups)} treatment groups -> {len(groups) * (len(groups) - 1) // 2} combinations")


if __name__ == "__main__":
    main()
